# Generated by Django 5.0.6 on 2026-05-30 05:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_task_assigned_to_project_task_project_standup'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='work_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
