# Generated by Django 5.0.6 on 2026-05-30 05:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_task_end_time_task_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='work_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='standup',
            name='work_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
