# Generated by Django 5.0.6 on 2026-06-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_dailyerror'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyerror',
            name='occurrence_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
