# Generated by Django 5.0.6 on 2026-06-01 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_dailyerror_occurrence_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='standup',
            name='review_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='standup',
            name='review_status',
            field=models.CharField(choices=[('Pending Review', 'Pending Review'), ('Reviewed', 'Reviewed'), ('Duplicate / Repeated', 'Duplicate / Repeated'), ('Needs Clarification', 'Needs Clarification')], default='Pending Review', max_length=40),
        ),
        migrations.AddField(
            model_name='standup',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='standup',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_standups', to=settings.AUTH_USER_MODEL),
        ),
    ]
