# Generated by Django 5.0.6 on 2026-06-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_message_recipient_standup_review_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=180)),
                ('purpose', models.CharField(blank=True, default='', max_length=180)),
                ('provider', models.CharField(blank=True, default='', max_length=120)),
                ('used_by_project', models.CharField(blank=True, default='', max_length=180)),
                ('owner', models.CharField(blank=True, default='', max_length=120)),
                ('recovery_contact', models.CharField(blank=True, default='', max_length=180)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('credential_location', models.CharField(blank=True, default='', max_length=160)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('last_reviewed', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['account'],
            },
        ),
        migrations.CreateModel(
            name='ITDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=180, unique=True)),
                ('registrar', models.CharField(blank=True, default='', max_length=120)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('dns_provider', models.CharField(blank=True, default='', max_length=120)),
                ('linked_project', models.CharField(blank=True, default='', max_length=180)),
                ('points_to', models.CharField(blank=True, default='', max_length=180)),
                ('ssl_provider', models.CharField(blank=True, default='', max_length=120)),
                ('ssl_expiry_date', models.DateField(blank=True, null=True)),
                ('renewal_owner', models.CharField(blank=True, default='', max_length=120)),
                ('auto_renew', models.BooleanField(default=False)),
                ('credential_location', models.CharField(blank=True, default='', max_length=160)),
                ('notes', models.TextField(blank=True, default='')),
                ('last_reviewed', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['domain_name'],
            },
        ),
        migrations.CreateModel(
            name='ITProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True)),
                ('project_type', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Maintenance', 'Maintenance'), ('Paused', 'Paused'), ('Deprecated', 'Deprecated')], default='Active', max_length=24)),
                ('owner', models.CharField(blank=True, default='', max_length=120)),
                ('developer', models.CharField(blank=True, default='', max_length=120)),
                ('client', models.CharField(blank=True, default='', max_length=120)),
                ('repo_url', models.URLField(blank=True, default='')),
                ('live_url', models.URLField(blank=True, default='')),
                ('staging_url', models.URLField(blank=True, default='')),
                ('tech_stack', models.TextField(blank=True, default='')),
                ('server', models.CharField(blank=True, default='', max_length=160)),
                ('database_name', models.CharField(blank=True, default='', max_length=160)),
                ('credential_location', models.CharField(blank=True, default='', max_length=160)),
                ('notes', models.TextField(blank=True, default='')),
                ('last_reviewed', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ITRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('category', models.CharField(blank=True, default='', max_length=80)),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Open', max_length=24)),
                ('owner', models.CharField(blank=True, default='', max_length=120)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('details', models.TextField(blank=True, default='')),
                ('resolution', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['status', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ITServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True)),
                ('provider', models.CharField(blank=True, default='', max_length=120)),
                ('ip_address', models.CharField(blank=True, default='', max_length=80)),
                ('environment', models.CharField(blank=True, default='Production', max_length=80)),
                ('os', models.CharField(blank=True, default='', max_length=120)),
                ('cpu', models.CharField(blank=True, default='', max_length=80)),
                ('ram', models.CharField(blank=True, default='', max_length=80)),
                ('disk', models.CharField(blank=True, default='', max_length=80)),
                ('ssh_user', models.CharField(blank=True, default='', max_length=80)),
                ('ssh_port', models.CharField(blank=True, default='', max_length=20)),
                ('hosted_projects', models.TextField(blank=True, default='')),
                ('backup_status', models.CharField(blank=True, default='', max_length=120)),
                ('monitoring_status', models.CharField(blank=True, default='', max_length=120)),
                ('credential_location', models.CharField(blank=True, default='', max_length=160)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('owner', models.CharField(blank=True, default='', max_length=120)),
                ('last_checked', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
