# Generated by Django 5.0.6 on 2026-06-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_itaccount_itdomain_itproject_itrisk_itserver'),
    ]

    operations = [
        migrations.AddField(
            model_name='itproject',
            name='backend_url',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='itproject',
            name='live_url',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='itproject',
            name='repo_url',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='itproject',
            name='staging_url',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
    ]
