# Generated by Django 5.0.6 on 2026-06-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_itproject_backend_url_alter_itproject_live_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('position', models.CharField(blank=True, default='', max_length=120)),
                ('department', models.CharField(blank=True, default='', max_length=120)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('manager', models.CharField(blank=True, default='', max_length=120)),
                ('access_level', models.CharField(blank=True, default='', max_length=120)),
                ('assigned_projects', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Inactive', 'Inactive')], default='Active', max_length=24)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
