# Generated by Django 5.0.6 on 2026-06-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_itemployee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITAISubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=160)),
                ('provider', models.CharField(blank=True, default='', max_length=120)),
                ('plan', models.CharField(blank=True, default='', max_length=120)),
                ('account_email', models.EmailField(blank=True, default='', max_length=254)),
                ('owner', models.CharField(blank=True, default='', max_length=120)),
                ('assigned_users', models.TextField(blank=True, default='')),
                ('monthly_cost', models.CharField(blank=True, default='', max_length=80)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('billing_cycle', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Trial', 'Trial'), ('Paused', 'Paused'), ('Cancelled', 'Cancelled')], default='Active', max_length=24)),
                ('credential_location', models.CharField(blank=True, default='', max_length=160)),
                ('usage_notes', models.TextField(blank=True, default='')),
                ('cancellation_notes', models.TextField(blank=True, default='')),
                ('last_reviewed', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tool_name'],
            },
        ),
    ]
