# Generated by Django 5.0.6 on 2026-06-01 09:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_itaisubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(default=django.utils.timezone.localdate)),
                ('topic', models.CharField(max_length=180)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('summary', models.TextField()),
                ('source', models.CharField(blank=True, default='', max_length=180)),
                ('time_spent_minutes', models.PositiveIntegerField(default=0)),
                ('confidence', models.CharField(choices=[('Started', 'Started'), ('Practicing', 'Practicing'), ('Confident', 'Confident')], default='Practicing', max_length=24)),
                ('next_step', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-work_date', '-created_at'],
            },
        ),
    ]
