# Generated by Django 5.0.6 on 2026-06-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_learningentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyerror',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Fixing', 'Fixing'), ('Investigating', 'Investigating'), ('Resolved', 'Resolved'), ('Prevented', 'Prevented')], default='Open', max_length=24),
        ),
    ]
