# Generated by Django 5.2.15 on 2026-06-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GatePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_no', models.CharField(db_index=True, max_length=20, unique=True)),
                ('direction', models.CharField(blank=True, max_length=50)),
                ('entry_type', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('path_str', models.CharField(blank=True, max_length=400)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=80)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('details', models.TextField(blank=True)),
                ('in_time', models.CharField(blank=True, max_length=40)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(default='Inside', max_length=20)),
                ('out_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headers', models.JSONField(default=list)),
                ('rows', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Structure',
            },
        ),
    ]
